### ISSUE TITLE
Create Plant Component

### ISSUE THREAD

**Issue by tborsa** [alumni-lab/garden-party#7]
Create a plant component, that takes in size and type of plant as props and will show the plant.
This will eventually be used in a garden component that shows all of the plants. For now ue emoji's for the plant image.
The component should take up a static amount of space say (ex. 100px by 100px) and as the plant grows it will overflow out of that space. 

Imagine rows of these piranha plant where the plant pot cannot overlap but the plant will overlap. 
![Custom Edited - Mario Customs - Piranha Plant (1)](https://user-images.githubusercontent.com/25540194/73143661-bd427800-4051-11ea-8a7e-1662f2deb0a3.png)

**Comment by charcharmasonjar** [comment]
![Screenshot 2020-02-11 at 7 14 46 PM](https://user-images.githubusercontent.com/49421048/74299923-01e13b00-4d03-11ea-8158-ada38e7f1c18.png)

Here's the garden filled with some plants. The plants are rendered based on fake data where the size of the plant is passed down to font-size.
